"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { swalInfo } from "@/lib/swal";
import type { FetchCandidateProfileOutput } from "@/types/types";

type TabKey =
  | "sentiment"
  | "personality"
  | "communication"
  | "interview"
  | "cultural"
  | "skills"
  | "transcript";

export default function CandidateProfile({
  candidateProfile,
}: {
  candidateProfile: FetchCandidateProfileOutput | null | undefined;
}) {
  const alertedRef = useRef(false);
  const [activeTab, setActiveTab] = useState<TabKey>("sentiment");

  useEffect(() => {
    if (!candidateProfile && !alertedRef.current) {
      alertedRef.current = true;
      swalInfo(
        "No Candidate Profile",
        "We couldn't load the candidate profile data. Please refresh or try again later.",
      );
    }
  }, [candidateProfile]);

  const tabs = useMemo(
    () =>
      [
        { key: "sentiment", label: "Sentiment" },
        { key: "personality", label: "Personality" },
        { key: "communication", label: "Communication" },
        { key: "interview", label: "Interview" },
        { key: "cultural", label: "Culture Fit" },
        { key: "skills", label: "Skill Gaps" },
        { key: "transcript", label: "Transcript" },
      ] as const,
    [],
  );

  const tabBtnBase =
    "px-3.5 py-2 rounded-xl text-sm font-semibold transition-all select-none border whitespace-nowrap";
  const tabBtnActive =
    "bg-[#E30022] text-white border-[#E30022] shadow-[0_12px_30px_rgba(227,0,34,0.25)]";
  const tabBtnInactive =
    "bg-white/40 text-slate-700 border-white/60 hover:bg-white/60 hover:border-white/80";

  return (
    <div className="w-full h-full relative overflow-hidden bg-linear-to-br from-red-50 via-white to-red-100">
      <div className="pointer-events-none absolute inset-0 -z-10">
        <div className="absolute -top-24 -left-24 h-80 w-80 rounded-full bg-red-300/25 blur-3xl" />
        <div className="absolute top-28 -right-24 h-96 w-96 rounded-full bg-red-200/25 blur-3xl" />
        <div className="absolute -bottom-28 left-1/3 h-112 w-md rounded-full bg-rose-400/15 blur-3xl" />
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_left,rgba(255,255,255,0.75),transparent_55%)]" />
      </div>

      <div className="w-full h-full p-6">
        <div className="h-full grid grid-cols-1 lg:grid-cols-12 gap-6">
          <div className="lg:col-span-6 h-full overflow-hidden rounded-3xl border border-white/60 bg-white/45 backdrop-blur-2xl shadow-[0_20px_70px_rgba(0,0,0,0.10)]">
            <div className="h-full overflow-y-auto p-7 space-y-6 scrollbar-thin scrollbar-thumb-red-200/80 scrollbar-track-transparent">
              <div className="flex items-start justify-between gap-4">
                <div>
                  <h2 className="text-lg font-bold text-slate-800 tracking-tight">
                    Candidate Score
                  </h2>
                  <p className="text-xs text-slate-600 mt-1">
                    Score generated by AI
                  </p>
                </div>
              </div>

              <div
                className="
                  rounded-2xl
                  border border-white/60
                  bg-white/40
                  backdrop-blur-2xl
                  shadow-[0_15px_40px_rgba(227,0,34,0.08)]
                  p-5
                "
              >
                <div className="flex items-start justify-between gap-4">
                  <div className="flex-1">
                    <span className="block text-sm font-semibold text-slate-700 mb-3">
                      Raw Score
                    </span>

                    <div className="flex items-center gap-3">
                      <div className="flex items-center gap-1">
                        {[...Array(5)].map((_, i) => (
                          <svg
                            key={i}
                            className={`w-5 h-5 drop-shadow-sm transition ${
                              i <
                              Math.floor(
                                candidateProfile?.score?.score_data
                                  ?.job_fit_stars || 0,
                              )
                                ? "text-[#E30022]"
                                : "text-red-200"
                            }`}
                            fill="currentColor"
                            viewBox="0 0 20 20"
                          >
                            <title>Star</title>
                            <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.184 3.642a1 1 0 00.95.69h3.813c.969 0 1.371 1.24.588 1.81l-3.087 2.243a1 1 0 00-.364 1.118l1.184 3.642c.3.921-.755 1.688-1.54 1.118L10 13.347l-3.087 2.243c-.785.57-1.84-.197-1.54-1.118l1.184-3.642a1 1 0 00-.364-1.118L3.106 9.07c-.783-.57-.38-1.81.588-1.81h3.813a1 1 0 00.95-.69l1.184-3.642z" />
                          </svg>
                        ))}
                      </div>

                      <span className="text-sm font-medium text-slate-600">
                        (
                        {candidateProfile?.score?.score_data?.job_fit_stars ||
                          0}
                        /5)
                      </span>
                    </div>
                  </div>

                  <button
                    type="button"
                    className="
                      shrink-0
                      px-4 py-2
                      rounded-xl
                      bg-gradient-to-r from-[#E30022] to-red-500
                      text-white
                      text-xs font-semibold
                      tracking-wide
                      shadow-lg shadow-red-500/20
                      hover:opacity-90
                      transition-all
                    "
                  >
                    RESCORE
                  </button>
                </div>
              </div>

              <div className="rounded-2xl border border-white/60 bg-white/35 backdrop-blur-xl shadow-md p-5">
                <span className="block text-sm font-semibold text-slate-700 mb-2">
                  Predictive Success
                </span>

                <div className="w-full bg-white/55 border border-white/70 h-3.5 rounded-full overflow-hidden shadow-inner">
                  <div
                    className="h-3.5 rounded-full bg-linear-to-r from-[#E30022] to-red-400 shadow-[0_10px_25px_rgba(227,0,34,0.35)]"
                    style={{
                      width: `${
                        candidateProfile?.score?.score_data
                          ?.predictive_success ?? 0
                      }%`,
                    }}
                  />
                </div>

                <span className="text-xs text-slate-600 mt-2 block">
                  {candidateProfile?.score?.score_data.predictive_success || 0}%
                  likelihood of success
                </span>
              </div>

              <div className="rounded-2xl border border-white/60 bg-white/35 backdrop-blur-xl shadow-md p-5">
                <span className="block text-sm font-semibold text-slate-700 mb-2">
                  Key Highlights
                </span>

                <ul className="list-disc ml-6 text-sm text-slate-700 space-y-1.5 marker:text-red-400">
                  {candidateProfile?.score?.score_data.phrases.map(
                    (phrase: string) => (
                      <li key={crypto.randomUUID()} className="leading-relaxed">
                        {phrase}
                      </li>
                    ),
                  )}
                </ul>
              </div>

              <div className="rounded-2xl border border-white/60 bg-white/35 backdrop-blur-xl shadow-md p-5">
                <span className="block text-sm font-semibold text-slate-700 mb-2">
                  Evaluation Summary
                </span>

                <p className="text-sm text-slate-700 leading-relaxed">
                  {candidateProfile?.score?.score_data.reason}
                </p>
              </div>
            </div>
          </div>

          <div className="lg:col-span-6 h-full overflow-hidden rounded-3xl border border-white/60 bg-white/45 backdrop-blur-2xl shadow-[0_20px_70px_rgba(0,0,0,0.10)]">
            <div className="h-full overflow-y-auto p-7 scrollbar-thin scrollbar-thumb-red-200/80 scrollbar-track-transparent">
              <div className="flex flex-col gap-4">
                <div className="flex items-start justify-between gap-4">
                  <div>
                    <h2 className="text-lg font-bold text-slate-800 tracking-tight">
                      Insights
                    </h2>
                    <p className="text-xs text-slate-600 mt-1">
                      Use tabs to explore different key insights
                    </p>
                  </div>
                </div>

                <div className="rounded-2xl border border-white/60 bg-white/35 backdrop-blur-xl p-2 shadow-sm">
                  <div className="flex flex-wrap gap-2 w-full">
                    {tabs.map((t) => (
                      <button
                        key={t.key}
                        onClick={() => setActiveTab(t.key)}
                        className={`${tabBtnBase} ${
                          activeTab === t.key ? tabBtnActive : tabBtnInactive
                        }`}
                        type="button"
                      >
                        {t.label}
                      </button>
                    ))}
                  </div>
                </div>
              </div>

              <div className="mt-6 space-y-5 text-sm text-slate-800">
                {activeTab === "sentiment" && (
                  <div className="space-y-5">
                    <div className="rounded-2xl border border-white/60 bg-white/35 backdrop-blur-xl shadow-md p-5">
                      <h3 className="font-bold text-slate-800 tracking-tight">
                        Sentiment Highlights
                      </h3>
                      {candidateProfile?.transcribed?.transcription
                        ?.sentimental_analysis_phrases ? (
                        <ul className="list-disc ml-6 mt-3 space-y-1.5 marker:text-red-400 text-slate-700">
                          {candidateProfile.transcribed.transcription.sentimental_analysis_phrases.map(
                            (phrase: string) => (
                              <li
                                key={crypto.randomUUID()}
                                className="leading-relaxed"
                              >
                                {phrase}
                              </li>
                            ),
                          )}
                        </ul>
                      ) : (
                        <p className="text-slate-600 mt-2">
                          No sentiment highlights available.
                        </p>
                      )}
                    </div>

                    <div className="rounded-2xl border border-white/60 bg-white/35 backdrop-blur-xl shadow-md p-5">
                      <h3 className="font-bold text-slate-800 tracking-tight">
                        Sentiment Analysis
                      </h3>
                      <p className="text-slate-700 leading-relaxed mt-2">
                        {candidateProfile?.transcribed?.transcription
                          ?.sentimental_analysis ||
                          "No sentiment analysis available."}
                      </p>
                    </div>
                  </div>
                )}

                {activeTab === "personality" && (
                  <div className="space-y-5">
                    <div className="rounded-2xl border border-white/60 bg-white/35 backdrop-blur-xl shadow-md p-5">
                      <h3 className="font-bold text-slate-800 tracking-tight">
                        Personality Highlights
                      </h3>
                      {candidateProfile?.transcribed?.transcription
                        ?.personality_traits_phrases ? (
                        <ul className="list-disc ml-6 mt-3 space-y-1.5 marker:text-red-400 text-slate-700">
                          {candidateProfile.transcribed.transcription.personality_traits_phrases.map(
                            (trait: string) => (
                              <li
                                key={crypto.randomUUID()}
                                className="leading-relaxed"
                              >
                                {trait}
                              </li>
                            ),
                          )}
                        </ul>
                      ) : (
                        <p className="text-slate-600 mt-2">
                          No personality highlights available.
                        </p>
                      )}
                    </div>

                    <div className="rounded-2xl border border-white/60 bg-white/35 backdrop-blur-xl shadow-md p-5">
                      <h3 className="font-bold text-slate-800 tracking-tight">
                        Personality Traits
                      </h3>
                      <p className="text-slate-700 leading-relaxed mt-2">
                        {candidateProfile?.transcribed?.transcription
                          ?.personality_traits ||
                          "No personality traits insights available."}
                      </p>
                    </div>
                  </div>
                )}

                {activeTab === "communication" && (
                  <div className="space-y-5">
                    <div className="rounded-2xl border border-white/60 bg-white/35 backdrop-blur-xl shadow-md p-5">
                      <h3 className="font-bold text-slate-800 tracking-tight">
                        Communication Highlights
                      </h3>
                      {candidateProfile?.transcribed?.transcription
                        ?.communication_style_insights_phrases ? (
                        <ul className="list-disc ml-6 mt-3 space-y-1.5 marker:text-red-400 text-slate-700">
                          {candidateProfile.transcribed.transcription.communication_style_insights_phrases.map(
                            (insight: string) => (
                              <li
                                key={crypto.randomUUID()}
                                className="leading-relaxed"
                              >
                                {insight}
                              </li>
                            ),
                          )}
                        </ul>
                      ) : (
                        <p className="text-slate-600 mt-2">
                          No communication highlights available.
                        </p>
                      )}
                    </div>

                    <div className="rounded-2xl border border-white/60 bg-white/35 backdrop-blur-xl shadow-md p-5">
                      <h3 className="font-bold text-slate-800 tracking-tight">
                        Communication Style
                      </h3>
                      <p className="text-slate-700 leading-relaxed mt-2">
                        {candidateProfile?.transcribed?.transcription
                          ?.communication_style_insights ||
                          "No communication style insights available."}
                      </p>
                    </div>
                  </div>
                )}

                {activeTab === "interview" && (
                  <div className="space-y-5">
                    <div className="rounded-2xl border border-white/60 bg-white/35 backdrop-blur-xl shadow-md p-5">
                      <h3 className="font-bold text-slate-800 tracking-tight">
                        Interview Highlights
                      </h3>
                      {candidateProfile?.transcribed?.transcription
                        ?.interview_insights_phrases ? (
                        <ul className="list-disc ml-6 mt-3 space-y-1.5 marker:text-red-400 text-slate-700">
                          {candidateProfile.transcribed.transcription.interview_insights_phrases.map(
                            (insight: string) => (
                              <li
                                key={crypto.randomUUID()}
                                className="leading-relaxed"
                              >
                                {insight}
                              </li>
                            ),
                          )}
                        </ul>
                      ) : (
                        <p className="text-slate-600 mt-2">
                          No interview highlights available.
                        </p>
                      )}
                    </div>
                    <div className="rounded-2xl border border-white/60 bg-white/35 backdrop-blur-xl shadow-md p-5">
                      <h3 className="font-bold text-slate-800 tracking-tight">
                        Interview Insights
                      </h3>
                      <p className="text-slate-700 leading-relaxed mt-2">
                        {candidateProfile?.transcribed?.transcription
                          ?.interview_insights ||
                          "No interview insights available."}
                      </p>
                    </div>
                  </div>
                )}

                {activeTab === "cultural" && (
                  <div className="space-y-5">
                    <div className="rounded-2xl border border-white/60 bg-white/35 backdrop-blur-xl shadow-md p-5">
                      <h3 className="font-bold text-slate-800 tracking-tight">
                        Cultural Fit Highlights
                      </h3>
                      {candidateProfile?.transcribed?.transcription
                        ?.cultural_fit_insights_phrases ? (
                        <ul className="list-disc ml-6 mt-3 space-y-1.5 marker:text-red-400 text-slate-700">
                          {candidateProfile.transcribed.transcription.cultural_fit_insights_phrases.map(
                            (insight: string) => (
                              <li
                                key={crypto.randomUUID()}
                                className="leading-relaxed"
                              >
                                {insight}
                              </li>
                            ),
                          )}
                        </ul>
                      ) : (
                        <p className="text-slate-600 mt-2">
                          No cultural fit highlights available.
                        </p>
                      )}
                    </div>

                    <div className="rounded-2xl border border-white/60 bg-white/35 backdrop-blur-xl shadow-md p-5">
                      <h3 className="font-bold text-slate-800 tracking-tight">
                        Cultural Fit Insights
                      </h3>
                      <p className="text-slate-700 leading-relaxed mt-2">
                        {candidateProfile?.transcribed?.transcription
                          ?.cultural_fit_insights ||
                          "No cultural fit insights available."}
                      </p>
                    </div>
                  </div>
                )}

                {activeTab === "skills" && (
                  <div className="space-y-5">
                    <div className="rounded-2xl border border-white/60 bg-white/35 backdrop-blur-xl shadow-md p-5">
                      <h3 className="font-bold text-slate-800 tracking-tight">
                        Skill Gaps Recommendations
                      </h3>
                      <p className="text-slate-700 leading-relaxed mt-2">
                        {candidateProfile?.score?.score_data
                          ?.skill_gaps_recommendations ||
                          "No skill gaps recommendations available."}
                      </p>
                    </div>
                  </div>
                )}
                {activeTab === "transcript" && (
                  <div className="space-y-5">
                    <div className="rounded-2xl border border-white/60 bg-white/35 backdrop-blur-xl shadow-md p-5">
                      <h3 className="font-bold text-slate-800 tracking-tight">
                        Full Transcription
                      </h3>

                      <div className="mt-3 rounded-2xl border border-white/60 bg-white/45 backdrop-blur-xl shadow-inner p-4">
                        <p className="text-slate-700 leading-relaxed whitespace-pre-wrap">
                          {candidateProfile?.transcribed?.transcription
                            ?.transcription || "No transcription available."}
                        </p>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
